name = "image-proxy"
main = "image-proxy.js"
compatibility_date = "2026-01-20"

workers_dev = false
routes = [
  { pattern = "https://trace.moe/image-proxy*", zone_name = "trace.moe" },
  { pattern = "https://www.trace.moe/image-proxy*", zone_name = "trace.moe" },
  { pattern = "https://www2.trace.moe/image-proxy*", zone_name = "trace.moe" }
]
